---
abstract: 'Create or update the website for http://ali.as/top100'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Remove: 1.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: CPAN::WWW::Top100::Generator
name: CPAN-WWW-Top100-Generator
no_index:
  directory:
    - inc
    - t
requires:
  CPANDB: 0.02
  File::Spec: 0.80
  HTML::Spry::DataSet: 0.01
  perl: 5.8.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/CPAN-WWW-Top100-Generator
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/CPAN-WWW-Top100-Generator
version: 0.06
